# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='friends.User')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='friends.User')),
            ],
        ),
    ]
